apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: category-crud
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: "10s"
        # autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: docker.io/marianemuniz/category-crud
          imagePullPolicy: Always